version: '3.4'
services:
  api:
    image: ghcr.io/danny-avila/librechat-dev:latest
    container_name: LibreChat_Demo1
    ports:
      - 3080:3080
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - ./logs:/app/api/logs
      - ./images:/app/client/public/images
    restart: always

  mongodb:
    container_name: chat-mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
    
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data:/meili_data
